server:
  port: ${PORT:31001}
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri: mongodb://root:Vv.340222@localhost:27017
      database: xc_cms
  rabbitmq:
    host: linux.humg.top
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  #热部署生效
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false
    settings:
      template_update_delay: 0
eureka:
  client:
    registerWithEureka: true  # 服务注册，是否将自己注册到Eureka服务中
    fetchRegistry: true   # 服务发现，是否从eureka中获取注册信息
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/}
  instance:
    prefer-ip-address: true   #将自己的ip注册到Eureka Server中
    instance-id: ${spring.application.name}:${server.port}
    ip-address: ${IP_ADDRESS:127.0.0.1}