server:
  port: 50101
spring:
  application:
    name: xc-govern-center
eureka:
  client:
    register-with-eureka: false  # 服务注册，是否将自己注册到Eureka服务中
    fetch-registry: false   # 服务发现，是否从eureka中获取注册信息
    service-url:
      defaultZone: http://localhost:50101/eureka/
  server:
    enable-self-preservation: false   # 是否开启自我保护模式
    eviction-interval-timer-in-ms: 60000    # 服务注册表清理间隔