server:
  port: 9000
spring:
  application:
    name: xc-service-manage-cms-client
  data:
    mongodb:
      uri: mongodb://root:Vv.340222@localhost:27017
      database: xc_cms
  rabbitmq:
    host: linux.humg.top
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  #热部署生效
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false
    settings:
      template_update_delay: 0
xuecheng:
  mq:
    queue: queue_cms_postpage_03
    routinKey: 609c8fdf689bc93304cb4c9e