server:
  port: 31200
spring:
  application:
    name: xc-service-manage-course
  datasource:
    druid:
      url: jdbc:mysql://linux.humg.top:3306/xc_course?characterEncoding=utf-8
      username: root
      password: Vv.340222
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
pagehelper:
  helper-dialect: mysql
eureka:
  client:
    register-with-eureka: true  # 服务注册，是否将自己注册到Eureka服务中
    fetch-registry: true   # 服务发现，是否从eureka中获取注册信息
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/}
  instance:
    prefer-ip-address: true   #将自己的ip注册到Eureka Server中
    instance-id: ${spring.application.name}:${server.port}
    ip-address: ${IP_ADDRESS:127.0.0.1}